services:
  client:
    build:
      context: ./client
    ports:
      - "8000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - api

  api:
    build:
      context: ./api
    env_file:
      - ./api/.env
    ports:
      - "5000:5000"